Repository Tech-Ping/EASY_STOCK-BE, pull requests merged in 2025-05, with the labels that each got.

#74 [Feat] 특정 주식의 투자자, 기업, 재무 정보 조회하는 기능 구현
  src/main/java/com/easystock/backend/application/service/inventory/InventoryServiceImpl.java
  src/main/java/com/easystock/backend/application/service/mypage/MyPageServiceImpl.java
  src/main/java/com/easystock/backend/application/service/stock/StockService.java
  src/main/java/com/easystock/backend/infrastructure/finance/kis/converter/KisStockConverter.java
  src/main/java/com/easystock/backend/infrastructure/finance/kis/response/KisStockAmountsOutputResponse.java
  src/main/java/com/easystock/backend/infrastructure/finance/kis/response/KisStockAmountsResponse.java
  src/main/java/com/easystock/backend/infrastructure/finance/kis/response/KisStockFinancialsOutputResponse.java
  src/main/java/com/easystock/backend/infrastructure/finance/kis/response/KisStockFinancialsResponse.java
  src/main/java/com/easystock/backend/infrastructure/finance/kis/response/KisStockMoneysOutputReponse.java
  src/main/java/com/easystock/backend/infrastructure/finance/kis/response/KisStockMoneysResponse.java
  src/main/java/com/easystock/backend/presentation/api/controller/StockController.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/StockConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/StockAmountResponse.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/StockFinancialResponse.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/StockInfoResponse.java
  src/main/java/com/easystock/backend/presentation/token/AuthUserArgumentResolver.java
Labels: ✨ FEATURE, 🍀 CHORE, 윤정, 🤚 PROGRESS

#86 [Release] 릴리즈 v1.1.1
  src/main/java/com/easystock/backend/application/service/mock/MockService.java
  src/main/java/com/easystock/backend/application/service/mock/MockServiceImpl.java
  src/main/java/com/easystock/backend/presentation/api/controller/MockController.java
  src/main/java/com/easystock/backend/presentation/api/dto/request/StokenRequest.java
  src/main/java/com/easystock/backend/presentation/api/payload/ApiResponse.java
Labels: 수정, RELEASE

#87 [Hofix] [Release] 릴리즈 v1.1.2
  src/main/java/com/easystock/backend/application/service/stock/StockInfoInitializeService.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/DailyProfit.java
  src/main/java/com/easystock/backend/util/FormatUtils.java
Labels: ⚠️ HOTFIX, 수정, RELEASE
