Repository Tech-Ping/EASY_STOCK-BE, pull requests merged in 2025-02, with the labels that each got.

#30 [Feat] 기업별 북마크 등록/해제 API 구현
  src/main/java/com/easystock/backend/application/service/bookmark/BookmarkService.java
  src/main/java/com/easystock/backend/application/service/bookmark/BookmarkServiceImpl.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/mapping/Bookmark.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/BookmarkRepository.java
  src/main/java/com/easystock/backend/presentation/api/controller/BookmarkController.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/BookmarkConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/request/BookmarkRequest.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/BookmarkResponse.java
  src/main/resources/db/migration/V2__insert_quiz_data.sql
Labels: ✨ FEATURE

#33 [Feat] 주식 호가, 잔량 조회 API 추가
  src/main/java/com/easystock/backend/application/service/stock/StockService.java
  src/main/java/com/easystock/backend/infrastructure/kis/converter/KisStockConverter.java
  src/main/java/com/easystock/backend/infrastructure/kis/response/KisStockQuotesOutput1Response.java
  src/main/java/com/easystock/backend/infrastructure/kis/response/KisStockQuotesOutput2Response.java
  src/main/java/com/easystock/backend/infrastructure/kis/response/KisStockQuotesResponse.java
  src/main/java/com/easystock/backend/presentation/api/controller/StockController.java
  src/main/java/com/easystock/backend/presentation/api/controller/TradeController.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/StockConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/StockQuotesResponse.java
Labels: ✨ FEATURE, 🛠️ REFACTORING, 🍀 CHORE, 윤정

#36 [Feat] 보유 주식 엔티티 정의
  src/main/java/com/easystock/backend/infrastructure/database/entity/Inventory.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/InventoryRepository.java
  src/main/java/com/easystock/backend/presentation/api/controller/TradeController.java
Labels: ✨ FEATURE, 윤정

#37 [Feat] 주식 주문 및 취소하는 API 추가
  src/main/java/com/easystock/backend/BackendApplication.java
  src/main/java/com/easystock/backend/application/service/stock/StockService.java
  src/main/java/com/easystock/backend/application/service/trade/TradeService.java
  src/main/java/com/easystock/backend/application/service/trade/TradeServiceImpl.java
  src/main/java/com/easystock/backend/aspect/exception/TradeException.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Inventory.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Trade.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/TradeRepository.java
  src/main/java/com/easystock/backend/presentation/api/controller/TradeController.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/InventoryConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/TradeConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/request/TradeRequest.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/TradeResultResponse.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/status/ErrorStatus.java
Labels: 📝 DOCS, ✨ FEATURE, 🍀 CHORE, 윤정

#41 [Refact] 주식 주문 체결 시에 포인트 정보 변경
  src/main/java/com/easystock/backend/application/service/stock/StockService.java
  src/main/java/com/easystock/backend/application/service/trade/TradeServiceImpl.java
  src/main/java/com/easystock/backend/aspect/exception/GeneralException.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Inventory.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Member.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/InventoryRepository.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/InventoryConverter.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/status/ErrorStatus.java
  src/main/resources/db/migration/V1__insert_stock_data.sql
Labels: 🪱 BUG, ✨ FEATURE, 🛠️ REFACTORING, 윤정

#44 [HOTFIX] cors 설정 추가
  src/main/java/com/easystock/backend/presentation/config/SecurityConfig.java
Labels: 🪱 BUG, ⚠️ HOTFIX
