Repository Tech-Ping/EASY_STOCK-BE, pull requests merged in 2025-01, with the labels that each got.

#2 [Docs] PR 템플릿 적용
  .github/pull_request_template.md
Labels: 📝 DOCS, ⚙️ SETTINGS

#5 [Feat] API 응답 형식 통일 & Swagger 세팅
  build.gradle
  src/main/java/com/easystock/backend/aspect/exception/ExceptionAdvice.java
  src/main/java/com/easystock/backend/aspect/exception/GeneralException.java
  src/main/java/com/easystock/backend/aspect/payload/ApiResponse.java
  src/main/java/com/easystock/backend/aspect/payload/code/BaseCode.java
  src/main/java/com/easystock/backend/aspect/payload/code/BaseErrorCode.java
  src/main/java/com/easystock/backend/aspect/payload/code/ErrorReasonDto.java
  src/main/java/com/easystock/backend/aspect/payload/code/ReasonDto.java
  src/main/java/com/easystock/backend/aspect/payload/code/status/ErrorStatus.java
  src/main/java/com/easystock/backend/aspect/payload/code/status/SuccessStatus.java
  src/main/java/com/easystock/backend/presentation/config/SecurityConfig.java
  src/main/java/com/easystock/backend/presentation/config/SwaggerConfig.java
Labels: 📝 DOCS, ⚙️ SETTINGS

#8 [Feat] 회원 인증/인가 로직 구현
  build.gradle
  src/main/java/com/easystock/backend/application/converter/MemberConverter.java
  src/main/java/com/easystock/backend/application/service/TokenService.java
  src/main/java/com/easystock/backend/application/service/TokenServiceImpl.java
  src/main/java/com/easystock/backend/application/service/auth/AuthService.java
  src/main/java/com/easystock/backend/application/service/auth/AuthServiceImpl.java
  src/main/java/com/easystock/backend/aspect/exception/AuthException.java
  src/main/java/com/easystock/backend/aspect/exception/ExceptionAdvice.java
  src/main/java/com/easystock/backend/aspect/exception/GeneralException.java
  src/main/java/com/easystock/backend/aspect/exception/JoinException.java
  src/main/java/com/easystock/backend/aspect/exception/TokenInvalidTypeException.java
  src/main/java/com/easystock/backend/aspect/exception/UnauthorizedTokenException.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Member.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/MemberRepository.java
  src/main/java/com/easystock/backend/presentation/api/controller/AuthController.java
  src/main/java/com/easystock/backend/presentation/api/controller/TokenTestController.java
  src/main/java/com/easystock/backend/presentation/api/dto/request/CreateMemberRequest.java
  src/main/java/com/easystock/backend/presentation/api/dto/request/LoginMemberRequest.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/CreateMemberResponse.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/LoginMemberResponse.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/TokenResponse.java
  src/main/java/com/easystock/backend/presentation/api/payload/ApiResponse.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/BaseCode.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/BaseErrorCode.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/ErrorReasonDto.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/ReasonDto.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/status/ErrorStatus.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/status/SuccessStatus.java
  src/main/java/com/easystock/backend/presentation/config/SwaggerConfig.java
  src/main/java/com/easystock/backend/presentation/properties/JwtProperties.java
  src/main/java/com/easystock/backend/presentation/token/JwtAuthenticationEntryPoint.java
  src/main/java/com/easystock/backend/presentation/token/MemberId.java
  src/main/java/com/easystock/backend/presentation/token/MemberIdArgumentResolver.java
  src/main/java/com/easystock/backend/presentation/token/UserAuthentication.java
  src/main/java/com/easystock/backend/presentation/token/filter/JwtAuthenticationFilter.java
  src/main/java/com/easystock/backend/presentation/token/jwt/JwtGenerator.java
  src/main/java/com/easystock/backend/presentation/token/jwt/JwtProvider.java
  src/main/java/com/easystock/backend/presentation/token/jwt/Token.java
  src/main/java/com/easystock/backend/presentation/token/jwt/TokenGenerator.java
  src/main/java/com/easystock/backend/presentation/token/jwt/TokenPair.java
  src/main/java/com/easystock/backend/presentation/token/jwt/TokenType.java
  src/main/java/com/easystock/backend/util/Constants.java
  src/main/resources/application.yml
Labels: 📝 DOCS, ✨ FEATURE, 🍀 CHORE

#10 [Feat] 마이페이지 내 프로필 정보 조회 API 구현
  build.gradle
  src/main/java/com/easystock/backend/BackendApplication.java
  src/main/java/com/easystock/backend/application/converter/MemberConverter.java
  src/main/java/com/easystock/backend/application/service/auth/AuthServiceImpl.java
  src/main/java/com/easystock/backend/application/service/mypage/MyPageService.java
  src/main/java/com/easystock/backend/application/service/mypage/MyPageServiceImpl.java
  src/main/java/com/easystock/backend/aspect/exception/ExceptionAdvice.java
  src/main/java/com/easystock/backend/aspect/payload/ApiResponse.java
  src/main/java/com/easystock/backend/aspect/payload/code/BaseCode.java
  src/main/java/com/easystock/backend/aspect/payload/code/BaseErrorCode.java
  src/main/java/com/easystock/backend/aspect/payload/code/ErrorReasonDto.java
  src/main/java/com/easystock/backend/aspect/payload/code/ReasonDto.java
  src/main/java/com/easystock/backend/aspect/payload/code/status/ErrorStatus.java
  src/main/java/com/easystock/backend/aspect/payload/code/status/SuccessStatus.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Member.java
  src/main/java/com/easystock/backend/presentation/api/controller/AuthController.java
  src/main/java/com/easystock/backend/presentation/api/controller/MyPageController.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/GetMemberProfileResponse.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/status/ErrorStatus.java
  src/main/java/com/easystock/backend/presentation/config/SecurityConfig.java
  src/main/java/com/easystock/backend/presentation/config/SwaggerConfig.java
  src/main/java/com/easystock/backend/presentation/config/WebConfig.java
  src/main/java/com/easystock/backend/presentation/token/AuthUser.java
  src/main/java/com/easystock/backend/presentation/token/AuthUserArgumentResolver.java
  src/main/java/com/easystock/backend/presentation/token/MemberIdArgumentResolver.java
  src/main/java/com/easystock/backend/presentation/token/filter/JwtAuthenticationFilter.java
  src/main/java/com/easystock/backend/presentation/token/jwt/JwtGenerator.java
  src/main/java/com/easystock/backend/presentation/token/jwt/JwtProvider.java
  src/main/java/com/easystock/backend/util/Constants.java
  src/main/resources/application.yml
  src/test/java/com/easystock/backend/BackendApplicationTests.java
  src/test/resources/application-test.yml
  ㅂ
Labels: 🪱 BUG, ✨ FEATURE, 🛠️ REFACTORING, 🍀 CHORE

#13 [Feat] 주식, 주문 엔티티 정의
  src/main/java/com/easystock/backend/infrastructure/database/entity/Stock.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Trade.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/enums/MarketType.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/enums/TradeStatus.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/enums/TradeType.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/StockRepository.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/TradeRepository.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/MemberConverter.java
Labels: ✨ FEATURE, 윤정

#18 [Hotfix] 마이페이지 API 스웨거 문서 typo 수정
  src/main/java/com/easystock/backend/presentation/api/controller/MyPageController.java
Labels: 📝 DOCS, ⚠️ HOTFIX

#19 [Feat] 주식 목록 조회하는 API 구현
  src/main/java/com/easystock/backend/application/service/auth/AuthServiceImpl.java
  src/main/java/com/easystock/backend/application/service/mypage/MyPageServiceImpl.java
  src/main/java/com/easystock/backend/application/service/stock/StockService.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Stock.java
  src/main/java/com/easystock/backend/infrastructure/kis/converter/KisStockConverter.java
  src/main/java/com/easystock/backend/infrastructure/kis/response/KisStockPricesOutputResponse.java
  src/main/java/com/easystock/backend/infrastructure/kis/response/KisStockPricesResponse.java
  src/main/java/com/easystock/backend/infrastructure/kis/response/KisTokenResponse.java
  src/main/java/com/easystock/backend/infrastructure/kis/token/KISTokenScheduler.java
  src/main/java/com/easystock/backend/infrastructure/kis/token/KISTokenService.java
  src/main/java/com/easystock/backend/presentation/api/controller/StockController.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/MemberConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/StockConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/StockPricesResponse.java
  src/main/java/com/easystock/backend/presentation/config/AppConfig.java
  src/main/java/com/easystock/backend/presentation/config/SecurityConfig.java
  src/main/java/com/easystock/backend/presentation/token/filter/JwtAuthenticationFilter.java
Labels: 🪱 BUG, ⚙️ SETTINGS, ✨ FEATURE, 🍀 CHORE, 윤정

#21 [Feat] 퀴즈 및 튜토리얼 완료 API 구현
  build.gradle
  src/main/java/com/easystock/backend/application/service/quiz/QuizService.java
  src/main/java/com/easystock/backend/application/service/quiz/QuizServiceImpl.java
  src/main/java/com/easystock/backend/application/service/stock/StockService.java
  src/main/java/com/easystock/backend/application/service/token/TokenService.java
  src/main/java/com/easystock/backend/application/service/token/TokenServiceImpl.java
  src/main/java/com/easystock/backend/application/service/tutorial/TutorialService.java
  src/main/java/com/easystock/backend/application/service/tutorial/TutorialServiceImpl.java
  src/main/java/com/easystock/backend/aspect/exception/QuizException.java
  src/main/java/com/easystock/backend/aspect/exception/TutorialException.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Member.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Quiz.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/mapping/MemberQuiz.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/MemberQuizRepository.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/MemberRepository.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/QuizRepository.java
  src/main/java/com/easystock/backend/infrastructure/kis/converter/KisStockConverter.java
  src/main/java/com/easystock/backend/infrastructure/kis/token/KISTokenScheduler.java
  src/main/java/com/easystock/backend/presentation/api/controller/QuizController.java
  src/main/java/com/easystock/backend/presentation/api/controller/TokenTestController.java
  src/main/java/com/easystock/backend/presentation/api/controller/TutorialController.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/MemberConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/QuizConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/TutorialConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/request/CompleteTutorialRequest.java
  src/main/java/com/easystock/backend/presentation/api/dto/request/QuizSubmitRequest.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/CompleteTutorialResponse.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/QuizSubmitResponse.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/status/ErrorStatus.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V2__insert_quiz_data.sql
Labels: ✨ FEATURE, 🍀 CHORE

#23 [Feat] 회원의 보유 주식, 주문 조회 API 추가
  src/main/java/com/easystock/backend/application/service/mypage/MyPageServiceImpl.java
  src/main/java/com/easystock/backend/application/service/trade/TradeService.java
  src/main/java/com/easystock/backend/application/service/trade/TradeServiceImpl.java
  src/main/java/com/easystock/backend/infrastructure/database/entity/Trade.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/TradeRepository.java
  src/main/java/com/easystock/backend/presentation/api/controller/TradeController.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/TradeConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/TradeResponse.java
Labels: ✨ FEATURE, 🍀 CHORE, 윤정

#25 [Feat] 주식 세부 정보 조회 API 추가
  src/main/java/com/easystock/backend/application/service/stock/StockService.java
  src/main/java/com/easystock/backend/aspect/exception/StockException.java
  src/main/java/com/easystock/backend/presentation/api/controller/StockController.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/status/ErrorStatus.java
Labels: ✨ FEATURE, 윤정

#27 [Feat] 경험치 정책에 의한 레벨업 API 구현
  src/main/java/com/easystock/backend/application/service/level/LevelService.java
  src/main/java/com/easystock/backend/application/service/level/LevelServiceImpl.java
  src/main/java/com/easystock/backend/application/service/quiz/QuizService.java
  src/main/java/com/easystock/backend/application/service/quiz/QuizServiceImpl.java
  src/main/java/com/easystock/backend/aspect/exception/LevelException.java
  src/main/java/com/easystock/backend/infrastructure/database/repository/MemberRepository.java
  src/main/java/com/easystock/backend/presentation/api/controller/LevelController.java
  src/main/java/com/easystock/backend/presentation/api/controller/MyPageController.java
  src/main/java/com/easystock/backend/presentation/api/controller/QuizController.java
  src/main/java/com/easystock/backend/presentation/api/controller/TradeController.java
  src/main/java/com/easystock/backend/presentation/api/controller/TutorialController.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/MemberConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/converter/QuizConverter.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/LevelUpResponse.java
  src/main/java/com/easystock/backend/presentation/api/dto/response/QuizSubmitResponse.java
  src/main/java/com/easystock/backend/presentation/api/payload/code/status/ErrorStatus.java
Labels: 🪱 BUG, 📝 DOCS, ✨ FEATURE, 🛠️ REFACTORING
